### ISSUE TITLE
Name of project

### ISSUE THREAD

**Issue by tbekolay** [vidartf/nbsphinx-link#1]
Hi! We started using this project and like the simplicity of it a lot.

One slight confusion I have is its name. The repository is named `nbsphinx-include`, but within the repo and on PyPI the name is `nbsphinx-link`. Which is the canonical name? Perhaps the repository should be renamed?

**Comment by vidartf** [comment]
Thanks for pointing it out! It started out with one name and was renamed half-way through initial development. Better to be consistent, so I've renamed it now.
