### ISSUE TITLE
nbsphinx-link on conda-feedstock

### ISSUE THREAD

**Issue by marimeireles** [vidartf/nbsphinx-link#13]
Hello!
I don't think you have a [conda-feedstock](https://github.com/conda-forge/?q=nbsphinx&type=&language=), right?
I'll create one and I'd like to know if you're interested in becoming a maintainer.  :)

Thanks! :cherry_blossom:

**Comment by marimeireles** [comment]
Here's the feedstock: https://github.com/conda-forge/staged-recipes/pull/12779

For conda is cool if you release a `tag` for each version you have on pypi because they have a bot that updates the conda-feedstock automatically for us, so we can keep everything in sync nicely.

**Comment by vidartf** [comment]
I see you created one now, and I've pushed the tag for the most recent release (and previous releases as well). Closing this as completed then.
