### ISSUE TITLE
Could not import extension nbsphinx-link

### ISSUE THREAD

**Issue by Blarc** [vidartf/nbsphinx-link#19]
When running ` make html`, I get the following error:

```
Running Sphinx v4.5.0

Extension error:
Could not import extension nbsphinx-link (exception: No module named 'nbsphinx-link')
make: *** [Makefile:20: html] Error 2
```

I have installed `nbsphinx-link` with `pip`, added it to extensions in `conf.py` and added it to `requirements.txt`.

Is `nbsphinx-link` not supported with Sphinx v4.5.0 ?

**Comment by hakonanes** [comment]
Can you try adding `nbsphinx_link` instead of `nbsphinx-link`?

**Comment by vidartf** [comment]
Closing, as I believe the solution suggested previously is the correct one (it is also what the README says).
