### ISSUE TITLE
give nbsphinx correct github binder links?

### ISSUE THREAD

**Issue by JohnGriffiths** [vidartf/nbsphinx-link#2]
Hi. 

Fantastic tool. Exactly what I needed. 

Is there a way to supply the correct filepath to the github binder link produced by the nbsphinx prologue?

As specified here:

https://github.com/spatialaudio/nbsphinx/blob/master/doc/conf.py

Example: the link at the top of this page

http://nbsphinx.readthedocs.io/en/0.3.3/markdown-cells.html

Thanks!

**Comment by vidartf** [comment]
I've opened a fix that I think should allow you to do what you want in #3. Does this do what you need, or maybe the path should be absolute?

Proposed usage:
```
{{ env.metadata[env.docname]['nbsphinx-link-target'] }}
```

**Comment by JohnGriffiths** [comment]
Thanks for the quick response. 

I tried this:

https://github.com/NeuroTechX/eeg-notebooks/commit/a723b0bccd9e5382abd79abdf16c21db1903bbd9


So the beginning of the section in the nbsphinx  `conf.py` now looks like


```python
nbsphinx_prolog = r"""
{% set docname = env.doc2path(env.docname, base='doc') %}
.. only:: html
    .. role:: raw-html(raw)
        :format: html
    .. nbinfo::
        This page was generated from `{{ env.metadata[env.docname]['nbsphinx-link-target'] }}`__.
        Interactive online version...:
```


Currently this doesn't seem to be working:

http://eeg-notebooks.readthedocs.io/en/latest/auditory_p300_with_muse.html

```
This page was generated from __. Interactive online version: :raw-html:`<a href=”https://mybinder.org/v2/gh/neurotechx/eeg-notebooks/eb40326”><img alt=”Binder badge” src=”https://mybinder.org/badge.svg” style=”vertical-align:text-bottom”></a>
```


Did I add the suggested fix correctly?


Ta.

**Comment by vidartf** [comment]
Sorry for the delay in coming back here. I added some docs for this package to the PR, which can serve as an example (and also added a config option for getting the metadata target to be relative to the right folders).
