### ISSUE TITLE
TypeError: add_source_parser() got an unexpected keyword argument 'override'

### ISSUE THREAD

**Issue by brbarkley** [vidartf/nbsphinx-link#5]
Installed nbsphinx-link 1.1.1 and getting following error when running sphinx-build...

`Exception occurred:
  File "..\site-packages\nbsphinx_link\__init__.py", line 89, in setup
    app.add_source_parser('.nblink', LinkedNotebookParser, override=True)
TypeError: add_source_parser() got an unexpected keyword argument 'override'
`

**Comment by vidartf** [comment]
Thanks for the report! Which versions of sphinx / nbsphinx do you have installed?

**Comment by vidartf** [comment]
The keyword in question seems to have been [added in sphinx 1.8](http://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_source_parser). If updating your sphinx version fixes the problem, I will specify the dependency version in setup.py.

**Comment by brbarkley** [comment]
Thanks for the quick reply! Seems likely that's the problem.

Versions:
- nbsphinx 0.3.5
- sphinx 1.7.9

**Comment by jasongrout** [comment]
FYI, it looks like the file extension form of `add_source_parser` is also deprecated in 1.8.

**Comment by vidartf** [comment]
Thanks. Then the resolution of this will be to specify the dependency version >= 1.8, and use the new `add_source_suffix` method instead.

**Comment by vidartf** [comment]
Added a fix in #8.
