### ISSUE TITLE
Broken with nbsphinx 0.4.1

### ISSUE THREAD

**Issue by ti250** [vidartf/nbsphinx-link#6]
Documentation which compiled in nbsphinx 0.3.5 no longer compiles as of nbsphinx 0.4.1, with error Notebook error:
No converter for suffix '.nblink'

**Comment by jasongrout** [comment]
I just ran into this too. It seems to come from a recent change in nbsphinx, the introduction of `nbsphinx_custom_formats` (https://github.com/spatialaudio/nbsphinx/pull/237, see https://github.com/spatialaudio/nbsphinx/pull/237/files#diff-4b6afd0fa4c9aae80ae389f523f5a1a5R797 for the line throwing the error). It looks like there may be a way to do this package's work with an nbsphinx option now? (Perhaps except for adding a dependency on the linked file?)

**Comment by jasongrout** [comment]
See also the new nbsphinx docs on custom formats: https://nbsphinx.readthedocs.io/en/0.4.1/custom-formats.html

**Comment by jasongrout** [comment]
or perhaps nbsphinx should pass the conversion function the document object, so the conversion function can do things like add the dependency?

**Comment by vidartf** [comment]
Maybe it will be sufficient to add a no-op converter?

**Comment by vidartf** [comment]
Added a fix in #8.
