### ISSUE TITLE
Relative path in notebook broken

### ISSUE THREAD

**Issue by jennirinker** [vidartf/nbsphinx-link#9]
Sorry I can't make a MWE, but it looks like any relative paths in the notebook aren't found.

E.g., here is my structure:
```
examples/
    ex1.ipynb
    data/
        data1.txt
docs/
    source/
(...)
```
and in `ex1.ipynb` I try to load the data using path `./data/data1.txt`. This works fine when running the notebook, but not when linking the docs. :(

**Comment by vidartf** [comment]
Note that nbsphinx-link does not currently execute the notebooks for you. You will have to execute the notebook and save it with the outputs you want before building the docs.

If this does not solve your problem, here are some questions that could help in troubleshooting this further: How do you load the data? What/how is it used? What did you expect to see, but did not?

**Comment by jennirinker** [comment]
You know what, I can't reproduce this error so I have no idea what I was talking about. I'm going to close this and I'll reopen it if I can recreate the issue in a MWE. Sorry for the trouble! And thanks for the quick response (and the package).
